# Production Environment Values
# Override default values for production environment

webapp:
  replicaCount: 3
  image:
    tag: "v6"
    pullPolicy: IfNotPresent
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

mysql:
  persistence:
    size: 10Gi
  
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

config:
  app:
    environment: "production"
    debugMode: false
    features:
      darkMode: true
      promotionalBanner: true
      advancedSearch: true

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70

# Production security hardening
securityContext:
  pod:
    fsGroup: 2000
    runAsNonRoot: true
  container:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop:
      - ALL

podDisruptionBudget:
  enabled: true
  minAvailable: 2

# Resource quotas and limits
backup:
  enabled: true
  schedule: "0 2 * * *"
  retention: "30d"
