apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  # Feature toggles
  FEATURE_DARK_MODE: "true"
  FEATURE_PROMOTIONAL_BANNER: "false"
  FEATURE_ADVANCED_SEARCH: "true"
  
  # Application settings
  APP_ENV: "production"
  APP_DEBUG: "false"
  LOG_LEVEL: "info"
  SESSION_TIMEOUT: "3600"
  MAX_UPLOAD_SIZE: "10M"
  
  # Health check settings
  HEALTH_CHECK_TIMEOUT: "3"
  DB_CONNECTION_TIMEOUT: "5"
