apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  containers:
  - name: load-generator
    image: busybox
    command: ['sh', '-c']
    args:
    - |
      echo "Starting load generation..."
      while true; do
        wget -q --spider http://website-service.default.svc.cluster.local || true
        sleep 0.01
      done
  restartPolicy: Never
