apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: default
type: Opaque
stringData:
  DB_HOST: mysql-service
  DB_NAME: ecomdb
  DB_USER: ecomuser
  DB_PASSWORD: ecompassword
