apiVersion: v1
kind: Service
metadata:
  name: website-service
  labels:
    app: ecom-website
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: ecom-website