name: PR Validation

on:
  pull_request:
    branches: [ main, master ]
    types: [opened, synchronize, reopened, ready_for_review]

env:
  DOCKER_REGISTRY: docker.io
  IMAGE_NAME: ecom-web

jobs:
  # ==============================================================================
  # LINT & VALIDATE JOB
  # ==============================================================================
  lint-and-validate:
    name: 🔍 Lint & Validate
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: 🔍 Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: docker/Dockerfile
          failure-threshold: warning
          
      - name: 🔍 Validate YAML Files
        run: |
          echo "🔍 Validating YAML syntax..."
          
          # Install yamllint
          pip install yamllint
          
          # Configure yamllint
          cat > .yamllint.yml << EOF
          extends: default
          rules:
            line-length:
              max: 120
            indentation:
              spaces: 2
            truthy:
              allowed-values: ['true', 'false', 'yes', 'no']
          EOF
          
          # Lint Kubernetes manifests
          yamllint k8s/ || echo "YAML lint completed with findings"
          
          # Lint Helm chart
          yamllint ecommerce-app/ || echo "Helm chart lint completed with findings"
          
      - name: 🐘 PHP Syntax Check
        run: |
          echo "🐘 Checking PHP syntax..."
          
          # Install PHP
          sudo apt-get update
          sudo apt-get install -y php-cli
          
          # Check PHP syntax
          find learning-app-ecommerce -name "*.php" -exec php -l {} \; | grep -E "(Errors|Parse error)" && exit 1 || echo "✅ PHP syntax check passed"
          
      - name: 🎯 Helm Chart Validation
        run: |
          echo "🎯 Validating Helm chart..."
          
          # Install Helm
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          
          # Lint Helm chart
          helm lint ecommerce-app/
          
          # Validate template rendering
          helm template test-release ecommerce-app/ > /tmp/helm-rendered.yaml
          
          echo "✅ Helm chart validation completed"

  # ==============================================================================
  # SECURITY SCAN JOB
  # ==============================================================================
  security-scan:
    name: 🔒 Security Scan
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: 🔒 Dockerfile Security Scan
        run: |
          echo "🔒 Scanning Dockerfile for security issues..."
          
          # Check for common security issues
          echo "Checking for root user usage..."
          if grep -q "USER root" docker/Dockerfile; then
            echo "⚠️  Warning: Root user detected in Dockerfile"
          fi
          
          echo "Checking for latest tag usage..."
          if grep -q ":latest" docker/Dockerfile; then
            echo "⚠️  Warning: 'latest' tag usage detected"
          fi
          
          echo "✅ Basic security scan completed"
          
      - name: 🔍 Secret Detection
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  # ==============================================================================
  # BUILD TEST JOB
  # ==============================================================================
  build-test:
    name: 🔨 Build Test
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: 🏗️ Test Docker Build
        uses: docker/build-push-action@v5
        with:
          context: ../
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: false
          tags: test-build:pr-${{ github.event.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ==============================================================================
  # KUBERNETES DRY RUN JOB
  # ==============================================================================
  k8s-dry-run:
    name: 🎯 K8s Dry Run
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4
        
      - name: 🎛️ Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'
          
      - name: 🔍 Kubernetes Dry Run
        run: |
          echo "🔍 Performing Kubernetes dry run..."
          
          # Validate all manifests
          for file in k8s/*.yaml; do
            if [[ -f "$file" && -s "$file" ]]; then
              echo "Validating $file"
              kubectl apply --dry-run=client -f "$file"
            fi
          done
          
          echo "✅ Kubernetes dry run completed successfully"

  # ==============================================================================
  # PR SUMMARY JOB
  # ==============================================================================
  pr-summary:
    name: 📋 PR Summary
    runs-on: ubuntu-latest
    needs: [lint-and-validate, security-scan, build-test, k8s-dry-run]
    if: always() && github.event.pull_request.draft == false
    
    steps:
      - name: 📋 Generate PR Summary
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const jobs = [
              { name: 'Lint & Validate', status: '${{ needs.lint-and-validate.result }}' },
              { name: 'Security Scan', status: '${{ needs.security-scan.result }}' },
              { name: 'Build Test', status: '${{ needs.build-test.result }}' },
              { name: 'K8s Dry Run', status: '${{ needs.k8s-dry-run.result }}' }
            ];
            
            const statusIcon = (status) => {
              switch(status) {
                case 'success': return '✅';
                case 'failure': return '❌';
                case 'cancelled': return '⏹️';
                case 'skipped': return '⏭️';
                default: return '❓';
              }
            };
            
            let summary = `## 🔍 PR Validation Summary\n\n`;
            summary += `| Check | Status | Result |\n`;
            summary += `|-------|--------|--------|\n`;
            
            jobs.forEach(job => {
              summary += `| ${job.name} | ${statusIcon(job.status)} | ${job.status} |\n`;
            });
            
            summary += `\n### 📊 Details\n`;
            summary += `- **PR**: #${context.issue.number} - ${pr.title}\n`;
            summary += `- **Author**: @${pr.user.login}\n`;
            summary += `- **Branch**: \`${pr.head.ref}\`\n`;
            summary += `- **Commit**: \`${pr.head.sha.substring(0, 7)}\`\n`;
            
            const allPassed = jobs.every(job => job.status === 'success');
            if (allPassed) {
              summary += `\n✅ **All checks passed!** This PR is ready for review.\n`;
            } else {
              summary += `\n⚠️ **Some checks failed.** Please review and fix the issues before merging.\n`;
            }
            
            // Update the PR description or create a comment
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: summary
            });
